function BDS00001 = importBalanceTXTfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BDS00001 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  BDS00001 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  BDS00001 = importfile("C:\Users\juliu\OneDrive\Paskaitos\Informacines sistemos medicinoje\2020 paskaitos\BalanceTestDB\SubjectsMeasurements\BDS00001.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 31-Jan-2020 15:39:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Times", "FxN", "FyN", "FzN", "MxNm", "MyNm", "MzNm", "COPxcm", "COPycm"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
BDS00001 = readtable(filename, opts);

end