function importBDSinfo = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  BDSINFO = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  BDSINFO = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  BDSINFO = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  BDSinfo = importfile("C:\Users\evafu\Documents\UVa\4Curso\InformationSystems\Balance\BDSinfo.xlsx", "Sheet1", [1, 1931]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-May-2022 11:31:33

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, 1931];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Trial", "Subject", "Vision"];
opts.VariableTypes = ["string", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "Trial", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Trial", "Vision"], "EmptyFieldRule", "auto");

% Import the data
BDSinfo = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    BDSinfo = [BDSinfo; tb]; %#ok<AGROW>
end

end